"""
0206 - Built-in Generic DOCX Report Adapter
Phase 20 & 21: Creates a clean, professional two-stage DOCX report from scratch using python-docx.
Completely decoupled from any proprietary external templates.
"""
from pathlib import Path
from typing import Dict, Any
import docx
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from reporting.adapters.base import BaseReportAdapter
from reporting.basic.builder import BasicReportBuilder
from reporting.advanced.builder import AdvancedReportBuilder
from core.evidence import EvidenceStore


class GenericDOCXReportAdapter(BaseReportAdapter):
    """Programmatically generates self-contained DOCX reports without external templates."""

    def render(self, session_data: Dict[str, Any], output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest = session_data.get("manifest", {})
        assessment = session_data.get("assessment", {})
        findings = session_data.get("findings", [])
        evidence_records = session_data.get("evidence_records", [])

        # Reconstruct or wrap store for builders
        store = EvidenceStore()
        for r in evidence_records:
            try:
                store.create(
                    source_artifact=r.get("source_artifact", "sample"),
                    source_type=r.get("source_type", "UNKNOWN"),
                    field=r.get("field", ""),
                    value=r.get("value"),
                    extractor=r.get("extractor", "Core"),
                    confidence=r.get("confidence", 1.0),
                    provenance=r.get("provenance"),
                    prefix="E",
                    domain=r.get("domain", "PE")
                )
            except Exception:
                pass

        part1 = BasicReportBuilder.build_part1_data(store, findings, assessment, manifest)
        part2 = AdvancedReportBuilder.build_part2_data(store, findings, assessment, manifest)

        doc = docx.Document()

        # Margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # Title
        title_p = doc.add_paragraph()
        run_title = title_p.add_run("0206 MALWARE ANALYSIS & FORENSIC REPORT")
        run_title.font.name = "Calibri"
        run_title.font.size = Pt(18)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(16, 44, 87)

        sub_p = doc.add_paragraph()
        run_sub = sub_p.add_run(f"Generated by 0206 Engine v{manifest.get('engine_version', '2.0.0')} | Case: {manifest.get('case_id', 'N/A')}")
        run_sub.font.size = Pt(10)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(100, 100, 100)

        # Overview Table
        doc.add_heading("1. Analysis Overview", level=1)
        meta_table = doc.add_table(rows=6, cols=2)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = False

        overview_data = [
            ("Target Sample", manifest.get("sample_filename", "Unknown")),
            ("File Size", f"{(manifest.get('sample_size_bytes') or 0):,} bytes"),
            ("SHA256 Hash", manifest.get("sample_hashes", {}).get("sha256", "N/A")),
            ("Threat Assessment", f"{assessment.get('threat_level', 'UNKNOWN')} (Score: {assessment.get('threat_score', 0)}/100)"),
            ("Malware Family / Class", assessment.get("classification", "Generic")),
            ("Analysis Timestamp (UTC)", manifest.get("start_time_utc", "N/A"))
        ]

        for i, (label, val) in enumerate(overview_data):
            r = meta_table.rows[i]
            r.cells[0].text = str(label or "")
            r.cells[1].text = str(val if val is not None else "N/A")
            r.cells[0].paragraphs[0].runs[0].font.bold = True
            r.cells[0].paragraphs[0].runs[0].font.size = Pt(9.5)
            r.cells[1].paragraphs[0].runs[0].font.size = Pt(9.5)

        # Executive narrative
        p_exec = doc.add_paragraph()
        p_exec.paragraph_format.space_before = Pt(8)
        run_exec = p_exec.add_run(assessment.get("summary", "No summary generated."))
        run_exec.font.size = Pt(10)

        # PART I: Basic Analysis
        doc.add_heading("PART I — Basic Triage Analysis", level=1)
        sample_id = part1["sample_identification"]
        p_id = doc.add_paragraph()
        p_id.add_run(f"Architecture: {sample_id.get('architecture')} | Subsystem: {sample_id.get('subsystem')} | Entry Point: {sample_id.get('entry_point')}")

        rep = part1["reputation"]
        doc.add_heading("Reputation", level=2)
        p_rep = doc.add_paragraph()
        if rep.get("status") == "COMPLETED":
            p_rep.add_run(f"Provider: {rep.get('provider')} | Detections: {rep.get('detection_ratio')}")
        else:
            p_rep.add_run(f"Status: [NOT_ANALYZED] ({rep.get('details', 'Offline mode')})")

        # PART II: Advanced Analysis
        doc.add_heading("PART II — Advanced Analysis", level=1)
        doc.add_heading("Static Code Triage", level=2)
        asm = part2["assembly_code"]
        p_asm = doc.add_paragraph()
        if asm.get("status") == "COMPLETED":
            p_asm.add_run(f"Disassembled {asm.get('instruction_count')} instructions from entry point.")
        else:
            p_asm.add_run(f"{asm.get('details')}")

        doc.add_heading("Network & C2 Analysis", level=2)
        net = part2["network_c2"]
        p_net = doc.add_paragraph()
        if net.get("status") == "COMPLETED":
            p_net.add_run(f"Events: {net.get('total_events')} | Beacon analysis: {net.get('beacon_analysis')}")
        else:
            p_net.add_run(f"{net.get('details')}")

        # Grounded Findings
        doc.add_heading("Grounded Technical Findings", level=1)
        if findings:
            find_table = doc.add_table(rows=len(findings) + 1, cols=5)
            headers = ["ID", "Status", "Domain", "Title", "Grounding Evidence"]
            for col_idx, h in enumerate(headers):
                cell = find_table.rows[0].cells[col_idx]
                cell.text = h
                cell.paragraphs[0].runs[0].font.bold = True
                cell.paragraphs[0].runs[0].font.size = Pt(9.5)

            for idx, f in enumerate(findings):
                row = find_table.rows[idx + 1]
                eids = ", ".join(f.get("source_evidence_ids", []) or f.get("evidence_ids", [])) or "None"
                st = f.get("status") or f.get("evidence_level") or "CAPABILITY"
                dom = f.get("domain") or f.get("category") or "PE"
                row.cells[0].text = str(f.get("finding_id", f"F-{idx+1}"))
                row.cells[1].text = str(st)
                row.cells[2].text = str(dom)
                row.cells[3].text = str(f.get("title", ""))
                row.cells[4].text = str(eids)
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8.5)

        # IOCs
        doc.add_heading("Indicators of Compromise", level=1)
        doc.add_paragraph(f"Host IOCs: {', '.join(assessment.get('host_iocs', [])) or 'None'}")
        doc.add_paragraph(f"Network IOCs: {', '.join(assessment.get('network_iocs', [])) or 'None'}")

        # Limitations
        doc.add_heading("Limitations & Unknowns", level=1)
        doc.add_paragraph("All findings grounded in non-destructive static and provided behavioral telemetry.")

        doc.save(str(output_path))
        return output_path
