"""
0206 - Built-in Generic DOCX Report Adapter
Phase 18 & 21: Creates a clean, professional two-stage DOCX report from scratch using python-docx.
Strictly follows the canonical 23-section report structure without requiring external or proprietary templates.
Unsupported sections are explicitly noted as [NOT_ANALYZED].
"""
from pathlib import Path
from typing import Dict, Any
import docx
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from reporting.adapters.base import BaseReportAdapter
from reporting.basic.builder import BasicReportBuilder
from reporting.advanced.builder import AdvancedReportBuilder
from core.evidence import EvidenceStore


class GenericDOCXReportAdapter(BaseReportAdapter):
    """Programmatically generates self-contained DOCX reports without external templates."""

    def render(self, session_data: Dict[str, Any], output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest = session_data.get("manifest", {})
        assessment = session_data.get("assessment", {})
        findings = session_data.get("findings", [])
        evidence_records = session_data.get("evidence_records", [])
        coverage = session_data.get("coverage") or assessment.get("coverage", {})

        # Reconstruct or wrap store for builders
        store = EvidenceStore()
        for r in evidence_records:
            try:
                store.create(
                    source_artifact=r.get("source_artifact", "sample"),
                    source_type=r.get("source_type", "UNKNOWN"),
                    field=r.get("field", ""),
                    value=r.get("value"),
                    extractor=r.get("extractor", "Core"),
                    confidence=r.get("confidence", 1.0),
                    provenance=r.get("provenance"),
                    prefix="E",
                    domain=r.get("domain", "PE")
                )
            except Exception:
                pass

        part1 = BasicReportBuilder.build_part1_data(store, findings, assessment, manifest)
        part2 = AdvancedReportBuilder.build_part2_data(store, findings, assessment, manifest)

        doc = docx.Document()

        # Margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # Title
        sample_id = part1["sample_identification"]
        title_p = doc.add_paragraph()
        run_title = title_p.add_run("0206 MALWARE ANALYSIS & FORENSIC REPORT")
        run_title.font.name = "Calibri"
        run_title.font.size = Pt(18)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(16, 44, 87)

        sub_p = doc.add_paragraph()
        run_sub = sub_p.add_run(
            f"Generated by 0206 Engine v{manifest.get('engine_version', '2.0.0')} | "
            f"Case: {manifest.get('case_id', 'N/A')} | "
            f"Sample: {sample_id.get('filename', 'Unknown')}"
        )
        run_sub.font.size = Pt(10)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(100, 100, 100)

        # Executive Metadata Table
        doc.add_heading("Executive Summary & Triage Overview", level=1)
        meta_table = doc.add_table(rows=6, cols=2)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = False

        overview_data = [
            ("Target Sample", manifest.get("sample_filename", "Unknown")),
            ("File Size", f"{(manifest.get('sample_size_bytes') or 0):,} bytes"),
            ("SHA256 Hash", manifest.get("sample_hashes", {}).get("sha256", "N/A")),
            ("Authoritative Threat Assessment", f"{assessment.get('threat_level', 'UNKNOWN')} (Score: {assessment.get('threat_score', 0)}/100)"),
            ("Malware Family / Class", assessment.get("classification", "Generic")),
            ("Analysis Timestamp (UTC)", manifest.get("start_time_utc", "N/A"))
        ]

        for i, (label, val) in enumerate(overview_data):
            r = meta_table.rows[i]
            r.cells[0].text = str(label or "")
            r.cells[1].text = str(val if val is not None else "N/A")
            r.cells[0].paragraphs[0].runs[0].font.bold = True
            r.cells[0].paragraphs[0].runs[0].font.size = Pt(9.5)
            r.cells[1].paragraphs[0].runs[0].font.size = Pt(9.5)

        p_exec = doc.add_paragraph()
        p_exec.paragraph_format.space_before = Pt(8)
        run_exec = p_exec.add_run(assessment.get("summary", "No summary generated."))
        run_exec.font.size = Pt(10)

        # ==========================================
        # PART I — BASIC ANALYSIS
        # ==========================================
        doc.add_heading("PART I — BASIC ANALYSIS", level=1)

        # 1. Summary
        doc.add_heading("1. Summary", level=2)
        p_summary = doc.add_paragraph()
        p_summary.add_run(f"Threat Score: {part1['summary'].get('threat_score', 0)}/100 ({part1['summary'].get('threat_level', 'UNKNOWN')})\n")
        p_summary.add_run(f"Classification: {part1['summary'].get('classification', 'Generic')}\n")
        p_summary.add_run(f"Key Functionality: {part1['summary'].get('key_functionality', 'N/A')}\n")
        p_summary.add_run(f"Suspected Purpose: {part1['summary'].get('purpose', 'N/A')}\n")
        p_summary.add_run(f"Assessment Status: {part1['summary'].get('status', '[NOT_CONFIRMED]')}")

        # 2. Identification / IOCs
        doc.add_heading("2. Identification / IOCs", level=2)
        doc.add_paragraph(
            f"Filename: {sample_id.get('filename')}\n"
            f"SHA256: {sample_id.get('sha256')}\n"
            f"SHA1: {sample_id.get('sha1')}\n"
            f"MD5: {sample_id.get('md5')}\n"
            f"File Size: {sample_id.get('file_size')} bytes\n"
            f"Architecture: {sample_id.get('architecture')} | Subsystem: {sample_id.get('subsystem')}\n"
            f"Entry Point RVA: {sample_id.get('entry_point')} | Image Base: {sample_id.get('image_base')}"
        )

        # 3. Reputation
        rep = part1["reputation"]
        doc.add_heading("3. Reputation", level=2)
        rep_status = rep.get("status", "NOT_ANALYZED")
        if rep_status == "COMPLETED":
            doc.add_paragraph(
                f"Provider: {rep.get('provider')} | Detections: {rep.get('detection_ratio')} | "
                f"First Seen: {rep.get('first_seen')} | Last Seen: {rep.get('last_seen')}"
            )
        elif rep_status in ("NOT_CHECKED", "SKIPPED_OFFLINE"):
            doc.add_paragraph(f"[{rep_status}] {rep.get('details', 'External lookup skipped in offline mode')}")
        elif rep_status == "NOT_FOUND":
            doc.add_paragraph("[NOT_FOUND] Hash not found in intelligence database (absence of intel != clean)")
        else:
            doc.add_paragraph(f"[NOT_ANALYZED] {rep.get('details', 'Reputation lookup skipped or offline mode')}")

        # 4. Static Properties Analysis
        static = part1.get("static_properties") or part1.get("basic_static", {})
        doc.add_heading("4. Static Properties Analysis", level=2)
        if static.get("status") == "COMPLETED":
            doc.add_paragraph(
                f"Sections Analyzed: {static.get('section_count', 0)}\n"
                f"Imports Identified: {static.get('import_count', 0)}\n"
                f"Suspicious URLs: {len(static.get('urls', []))} | Suspicious IPs: {len(static.get('ips', []))}"
            )
        else:
            doc.add_paragraph("[NOT_ANALYZED] No static PE structure analyzed.")

        # 5. Basic Behavioral Analysis
        behav = part1["basic_behavioral"]
        doc.add_heading("5. Basic Behavioral Analysis", level=2)
        if behav.get("status") == "COMPLETED":
            doc.add_paragraph(
                f"Analysis Mode: {behav.get('mode', 'Artifact Ingestion')}\n"
                f"Processes Spawned: {behav.get('processes_spawned')}\n"
                f"File System Events: {behav.get('file_events')}\n"
                f"Registry Events: {behav.get('registry_events')}\n"
                f"Execution Safety: {behav.get('details', 'Artifact ingestion; no live execution conducted on host.')}"
            )
        else:
            doc.add_paragraph(f"[NOT_ANALYZED] {behav.get('details', 'No behavioral artifacts provided')}")

        # 6. Initial Findings
        doc.add_heading("6. Initial Findings", level=2)
        if findings:
            find_table = doc.add_table(rows=len(findings) + 1, cols=5)
            headers = ["Finding ID", "Status", "Domain", "Title", "Grounding Evidence"]
            for col_idx, h in enumerate(headers):
                cell = find_table.rows[0].cells[col_idx]
                cell.text = h
                cell.paragraphs[0].runs[0].font.bold = True
                cell.paragraphs[0].runs[0].font.size = Pt(9)

            for idx, f in enumerate(findings):
                row = find_table.rows[idx + 1]
                eids = ", ".join(f.get("source_evidence_ids", []) or f.get("evidence_ids", [])) or "None"
                st = f.get("status") or f.get("evidence_level") or "CAPABILITY"
                dom = f.get("domain") or f.get("category") or "PE"
                row.cells[0].text = str(f.get("finding_id", f"F-{idx+1}"))
                row.cells[1].text = str(st)
                row.cells[2].text = str(dom)
                row.cells[3].text = str(f.get("title", ""))
                row.cells[4].text = str(eids)
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8.5)
        else:
            doc.add_paragraph("[NOT_ANALYZED] No initial findings identified.")

        # 7. Initial Assessment
        doc.add_heading("7. Initial Assessment", level=2)
        doc.add_paragraph(
            f"Summary: {assessment.get('summary', 'N/A')}\n"
            f"Key Functionality: {assessment.get('key_functionality', 'N/A')}\n"
            f"Suspected Purpose: {assessment.get('purpose', 'N/A')}"
        )

        # ==========================================
        # PART II — ADVANCED ANALYSIS
        # ==========================================
        doc.add_heading("PART II — ADVANCED ANALYSIS", level=1)

        # 8. Advanced Static Analysis
        doc.add_heading("8. Advanced Static Analysis", level=2)
        doc.add_paragraph(str(part2["advanced_static"].get("details", "[NOT_ANALYZED]")))

        # 9. Assembly / Code Analysis
        doc.add_heading("9. Assembly / Code Analysis", level=2)
        asm = part2["assembly_code"]
        if asm.get("status") == "COMPLETED":
            doc.add_paragraph(f"Disassembled {asm.get('instruction_count')} instructions from entry point.")
        else:
            doc.add_paragraph(str(asm.get("details", "[NOT_ANALYZED]")))

        # 10. API / Control Flow
        doc.add_heading("10. API / Control Flow", level=2)
        doc.add_paragraph(str(part2["api_control_flow"].get("details", "[NOT_ANALYZED]")))

        # 11. Advanced Behavioral Analysis
        doc.add_heading("11. Advanced Behavioral Analysis", level=2)
        doc.add_paragraph(str(part2["advanced_dynamic"].get("details", "[NOT_ANALYZED]")))

        # 12. Process / Thread
        doc.add_heading("12. Process / Thread", level=2)
        doc.add_paragraph(str(part2["process_thread"].get("details", "[NOT_ANALYZED]")))

        # 13. Memory
        doc.add_heading("13. Memory", level=2)
        doc.add_paragraph(str(part2["memory_analysis"].get("details", "[NOT_ANALYZED]")))

        # 14. Network / C2
        doc.add_heading("14. Network / C2", level=2)
        net = part2["network_c2"]
        if net.get("status") == "COMPLETED":
            doc.add_paragraph(
                f"Captured Events: {net.get('total_events')}\n"
                f"DNS Queries: {', '.join(net.get('dns_queries', [])) or 'None'}\n"
                f"Beacon Assessment: {net.get('beacon_analysis')}"
            )
        else:
            doc.add_paragraph(str(net.get("details", "[NOT_ANALYZED]")))

        # 15. Persistence
        doc.add_heading("15. Persistence", level=2)
        doc.add_paragraph(str(part2["persistence"].get("details", "[NOT_ANALYZED]")))

        # 16. Anti-Analysis
        doc.add_heading("16. Anti-Analysis", level=2)
        doc.add_paragraph(str(part2["anti_analysis"].get("details", "[NOT_ANALYZED]")))

        # 17. Packing / Unpacking
        doc.add_heading("17. Packing / Unpacking", level=2)
        doc.add_paragraph(str(part2["unpacking"].get("details", "[NOT_ANALYZED]")))

        # 18. .NET / Scripts / Documents where applicable
        doc.add_heading("18. .NET / Scripts / Documents where applicable", level=2)
        doc.add_paragraph(str(part2["dotnet_scripts_docs"].get("details", "[NOT_APPLICABLE] Native executable target.")))

        # 19. Cross-Stage Correlation
        doc.add_heading("19. Cross-Stage Correlation", level=2)
        doc.add_paragraph(str(part2["cross_stage_correlation"].get("details", "[NOT_CONFIRMED] No cross-stage corroboration detected.")))

        # 20. Final Assessment
        doc.add_heading("20. Final Assessment", level=2)
        doc.add_paragraph(
            f"Authoritative Threat Score: {assessment.get('threat_score', 0)}/100 ({assessment.get('threat_level', 'UNKNOWN')})\n"
            f"Malware Family / Classification: {assessment.get('classification', 'Generic')}\n"
            f"Confidence Score: {assessment.get('confidence', 0.0):.2f}\n"
            f"Executive Rationale: {assessment.get('summary', 'N/A')}"
        )

        # ==========================================
        # APPENDICES (Sections 21-25)
        # ==========================================
        # 21. Indicators of Compromise (IOC)
        doc.add_heading("21. Indicators of Compromise (IOC)", level=1)
        doc.add_paragraph(f"Host IOCs: {', '.join(assessment.get('host_iocs', [])) or 'None'}")
        doc.add_paragraph(f"Network IOCs: {', '.join(assessment.get('network_iocs', [])) or 'None'}")

        # 22. MITRE ATT&CK
        doc.add_heading("22. MITRE ATT&CK", level=1)
        mitre_entries = assessment.get("mitre_techniques", [])
        if mitre_entries:
            mitre_table = doc.add_table(rows=len(mitre_entries) + 1, cols=5)
            m_headers = ["Technique ID", "Technique Name", "Tactic", "Status", "Citing Evidence"]
            for col_idx, h in enumerate(m_headers):
                cell = mitre_table.rows[0].cells[col_idx]
                cell.text = h
                cell.paragraphs[0].runs[0].font.bold = True
                cell.paragraphs[0].runs[0].font.size = Pt(9)

            for idx, m in enumerate(mitre_entries):
                row = mitre_table.rows[idx + 1]
                eids = ", ".join(m.get("evidence_ids", [])) or "None"
                row.cells[0].text = str(m.get("technique_id", "N/A"))
                row.cells[1].text = str(m.get("technique_name", "N/A"))
                row.cells[2].text = str(m.get("tactic", "N/A"))
                row.cells[3].text = str(m.get("status", "NOT_CONFIRMED"))
                row.cells[4].text = str(eids)
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8.5)
        else:
            doc.add_paragraph("[NOT_ANALYZED] No MITRE techniques mapped.")

        # 23. Coverage
        doc.add_heading("23. Coverage", level=1)
        cov_data = part2.get("coverage", {})
        cov_ratio = cov_data.get("ratio", "N/A") if isinstance(cov_data, dict) else "N/A"
        cov_domains = cov_data.get("domain_coverage", {}) if isinstance(cov_data, dict) else {}
        doc.add_paragraph(f"Overall Coverage Ratio: {cov_ratio}")
        if cov_domains:
            cov_p = doc.add_paragraph()
            for dom, st in list(cov_domains.items())[:12]:
                cov_p.add_run(f"• {dom}: {st}\n")

        # 24. Evidence Appendix
        doc.add_heading("24. Evidence Appendix", level=1)
        if evidence_records:
            ev_table = doc.add_table(rows=min(len(evidence_records), 30) + 1, cols=4)
            ev_headers = ["Evidence ID", "Domain", "Field", "State"]
            for col_idx, h in enumerate(ev_headers):
                cell = ev_table.rows[0].cells[col_idx]
                cell.text = h
                cell.paragraphs[0].runs[0].font.bold = True
                cell.paragraphs[0].runs[0].font.size = Pt(9)

            for idx, r in enumerate(evidence_records[:30]):
                row = ev_table.rows[idx + 1]
                row.cells[0].text = str(r.get("evidence_id", "N/A"))
                row.cells[1].text = str(r.get("domain", "PE"))
                row.cells[2].text = str(r.get("field", "N/A"))
                row.cells[3].text = str(r.get("state", "OBSERVED"))
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8)
        else:
            doc.add_paragraph("[NOT_ANALYZED] No evidence records cataloged.")

        # 25. Analysis Manifest
        doc.add_heading("25. Analysis Manifest", level=1)
        doc.add_paragraph(
            f"Engine: {manifest.get('engine_name', '0206')} v{manifest.get('engine_version', '2.0.0')}\n"
            f"Python Version: {manifest.get('python_version', '3.x')} | Host Platform: {manifest.get('host_platform', 'Linux')}\n"
            f"Profile: {manifest.get('profile', 'basic')} | Privacy Mode: {manifest.get('privacy_mode', 'strict')}\n"
            f"Duration: {(manifest.get('duration_ms') or 0.0):.2f} ms | SHA256: {manifest.get('sample_sha256', 'N/A')}"
        )

        doc.save(str(output_path))
        return output_path
