"""
0206 - Two-Stage Markdown Report Adapter
Phase 20 & 22: Renders evidence-grounded findings into GitHub-flavored Markdown following the canonical two-stage report structure.
"""
from pathlib import Path
from typing import Dict, Any, List
from reporting.adapters.base import BaseReportAdapter
from reporting.basic.builder import BasicReportBuilder
from reporting.advanced.builder import AdvancedReportBuilder
from core.evidence import EvidenceStore


class MarkdownReportAdapter(BaseReportAdapter):
    """Renders session findings into standalone two-stage Markdown report."""

    def render(self, session_data: Dict[str, Any], output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest = session_data.get("manifest", {})
        assessment = session_data.get("assessment", {})
        findings = session_data.get("findings", [])
        evidence_records = session_data.get("evidence_records", [])
        coverage = session_data.get("coverage", {})

        # Reconstruct or wrap store for builders
        store = EvidenceStore()
        for r in evidence_records:
            try:
                store.create(
                    source_artifact=r.get("source_artifact", "sample"),
                    source_type=r.get("source_type", "UNKNOWN"),
                    field=r.get("field", ""),
                    value=r.get("value"),
                    extractor=r.get("extractor", "Core"),
                    confidence=r.get("confidence", 1.0),
                    provenance=r.get("provenance"),
                    prefix="E",
                    domain=r.get("domain", "PE")
                )
            except Exception:
                pass

        part1 = BasicReportBuilder.build_part1_data(store, findings, assessment, manifest)
        part2 = AdvancedReportBuilder.build_part2_data(store, findings, assessment, manifest)

        sample_id = part1["sample_identification"]
        rep = part1["reputation"]
        static = part1["basic_static"]
        behav = part1["basic_behavioral"]

        lines = [
            f"# 0206 Malware Analysis Report: {sample_id.get('filename', 'Unknown Sample')}",
            "",
            f"> **Generated by:** {manifest.get('engine_name', '0206')} v{manifest.get('engine_version', '2.0.0')}  ",
            f"> **Case ID:** `{manifest.get('case_id', 'N/A')}`  ",
            f"> **Analysis Date:** `{manifest.get('start_time_utc', 'N/A')}`  ",
            f"> **Threat Score:** `{assessment.get('threat_score', 0)}/100` ({assessment.get('threat_level', 'UNKNOWN')})  ",
            f"> **Classification:** `{assessment.get('classification', 'Generic')}`",
            "",
            "---",
            "",
            "## PART I — BASIC ANALYSIS",
            "",
            "### 1. Sample Identification",
            "",
            f"- **Filename:** `{sample_id.get('filename')}`",
            f"- **SHA256:** `{sample_id.get('sha256')}`",
            f"- **SHA1:** `{sample_id.get('sha1')}`",
            f"- **MD5:** `{sample_id.get('md5')}`",
            f"- **File Size:** `{sample_id.get('file_size')} bytes`",
            f"- **Architecture / Subsystem:** `{sample_id.get('architecture')} | {sample_id.get('subsystem')}`",
            f"- **Entry Point RVA:** `{sample_id.get('entry_point')}`",
            f"- **Image Base:** `{sample_id.get('image_base')}`",
            "",
            "### 2. Reputation Assessment",
            "",
        ]

        if rep.get("status") == "COMPLETED":
            lines.extend([
                f"- **Provider:** {rep.get('provider')}",
                f"- **Detection Ratio:** `{rep.get('detection_ratio')}`",
                f"- **First Seen:** `{rep.get('first_seen')}`",
                f"- **Last Analysis:** `{rep.get('last_seen')}`",
                f"- **Privacy Policy:** `{rep.get('privacy_mode')}`",
            ])
        else:
            lines.append(f"- **Reputation Status:** `[NOT_ANALYZED]` ({rep.get('details', 'Reputation lookup skipped')})")

        lines.extend([
            "",
            "### 3. Basic Static Analysis",
            "",
            f"- **Sections Analyzed:** {static.get('section_count', 0)} sections",
            f"- **Imports Identified:** {static.get('import_count', 0)} routines",
            f"- **Suspicious URLs:** {len(static.get('urls', []))} extracted",
            f"- **Suspicious IPs:** {len(static.get('ips', []))} extracted",
            f"- **API Hashing Candidates:** {len(static.get('api_hashes', []))} identified",
            "",
            "### 4. Basic Behavioral Analysis",
            "",
        ])

        if behav.get("status") == "COMPLETED":
            lines.extend([
                f"- **Processes Spawned:** {behav.get('processes_spawned')}",
                f"- **File System Modifications:** {behav.get('file_events')}",
                f"- **Registry Modifications:** {behav.get('registry_events')}",
            ])
        else:
            lines.append(f"- **Behavioral Status:** `[NOT_ANALYZED]` ({behav.get('details')})")

        lines.extend([
            "",
            "### 5. Preliminary Findings",
            "",
            "| Finding ID | Status | Category | Title | Grounding Evidence | MITRE |",
            "| :--- | :---: | :--- | :--- | :--- | :---: |"
        ])

        for f in findings:
            eids = ", ".join(f.get("source_evidence_ids", []) or f.get("evidence_ids", [])) or "None"
            mitre = f.get("mitre_attack_id") or "N/A"
            status = f.get("status") or f.get("evidence_level") or "CAPABILITY"
            lines.append(
                f"| `{f.get('finding_id')}` | **{status}** | {f.get('category') or f.get('domain')} | {f.get('title')} | `{eids}` | `{mitre}` |"
            )

        lines.extend([
            "",
            "### 6. Initial Triage Assessment",
            "",
            f"**Executive Summary:** {assessment.get('summary', 'No summary generated.')}",
            "",
            f"**Key Functionality:** {assessment.get('key_functionality', 'N/A')}",
            "",
            f"**Suspected Purpose:** {assessment.get('purpose', 'N/A')}",
            "",
            "---",
            "",
            "## PART II — ADVANCED ANALYSIS",
            "",
            "### 7. Advanced Static Analysis",
            "",
            f"{part2['advanced_static'].get('details')}",
            "",
            "### 8. Assembly & Code Analysis (Static Triage)",
            "",
        ])

        asm = part2["assembly_code"]
        if asm.get("status") == "COMPLETED":
            lines.append(f"Disassembled {asm.get('instruction_count')} instructions from entry point.")
            lines.append("```assembly")
            for instr in asm.get("instructions_preview", []):
                lines.append(instr)
            lines.append("```")
        else:
            lines.append(f"{asm.get('details')}")

        lines.extend([
            "",
            "### 9. API & Control Flow Analysis",
            "",
            f"{part2['api_control_flow'].get('details', 'Analyzed dynamic resolution candidates.')}",
            "",
            "### 10. Advanced Dynamic & Process Analysis",
            "",
            f"{part2['advanced_dynamic_process'].get('details', 'Process trees and execution tracking.')}",
            "",
            "### 11. Memory Analysis",
            "",
            f"{part2['memory_analysis'].get('details')}",
            "",
            "### 12. Network & C2 Analysis",
            "",
        ])

        net = part2["network_c2"]
        if net.get("status") == "COMPLETED":
            lines.append(f"- **Total Captured Events:** {net.get('total_events')}")
            lines.append(f"- **DNS Queries:** {', '.join(net.get('dns_queries', [])) or 'None'}")
            lines.append(f"- **Beaconing Assessment:** {net.get('beacon_analysis')}")
        else:
            lines.append(f"{net.get('details')}")

        lines.extend([
            "",
            "### 13. Persistence Analysis",
            "",
            f"{part2['persistence'].get('details', 'Persistence mechanisms evaluated.')}",
            "",
            "### 14. Anti-Analysis & Defense Evasion",
            "",
            f"{part2['anti_analysis'].get('details')}",
            "",
            "### 15. Unpacking & Obfuscation",
            "",
            f"{part2['unpacking'].get('details')}",
            "",
            "### 16. Cross-Stage Correlation & Final Synthesis",
            "",
            f"{part2['cross_stage_correlation'].get('correlation_summary')}",
            "",
            "---",
            "",
            "## 17. Indicators of Compromise (Grounded IOCs)",
            "",
            "### Host-based Indicators",
            ""
        ])

        host_iocs = assessment.get("host_iocs", [])
        if host_iocs:
            for h in host_iocs:
                lines.append(f"- `{h}`")
        else:
            lines.append("- *No confirmed host IOCs identified.*")

        lines.extend([
            "",
            "### Network-based Indicators",
            ""
        ])
        net_iocs = assessment.get("network_iocs", [])
        if net_iocs:
            for n in net_iocs:
                lines.append(f"- `{n}`")
        else:
            lines.append("- *No confirmed network IOCs identified.*")

        lines.extend([
            "",
            "---",
            "",
            "## 18. MITRE ATT&CK Mapping",
            "",
            "| Technique ID | Technique Name | Tactic | Citing Evidence |",
            "| :--- | :--- | :--- | :--- |"
        ])

        for m in assessment.get("mitre_techniques", []):
            eids = ", ".join(m.get("evidence_ids", []))
            lines.append(
                f"| `{m.get('technique_id')}` | {m.get('technique_name')} | {m.get('tactic')} | `{eids}` |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 19. Analysis Coverage Matrix",
            "",
            "| Analysis Domain | Status | Observations |",
            "| :--- | :---: | :--- |"
        ])

        cov_matrix = coverage.get("domain_coverage", {})
        if cov_matrix:
            for dom, st in cov_matrix.items():
                lines.append(f"| {dom} | **{st}** | Standard profile execution |")
        else:
            default_domains = [
                ("PE Static", "COMPLETED"),
                ("Code Triage", "COMPLETED"),
                ("Reputation", rep.get("status", "NOT_ANALYZED")),
                ("Behavioral", behav.get("status", "NOT_ANALYZED")),
                ("Network", net.get("status", "NOT_ANALYZED")),
                ("Memory", "NOT_AVAILABLE"),
                ("Unpacking", "NOT_ANALYZED"),
            ]
            for dom, st in default_domains:
                lines.append(f"| {dom} | **{st}** | Automated triage evaluation |")

        lines.extend([
            "",
            "---",
            "",
            "## 20. Limitations & Analytical Priorities",
            "",
            "- **Zero-Execution Host Safety:** Static code disassembly and behavioral triage artifacts were ingested without live hostile detonation on the analyst machine.",
            "- **API Resolution Limits:** Dynamic imports obfuscated via custom run-time hashing or PEB walking require interactive debugger tracing.",
            "- **Network Telemetry:** Streamed PCAP captures represent recorded lab sessions; inactive C2 domains could not be contacted in offline mode.",
            "",
            "---",
            "",
            "## 21. Evidence Appendix",
            "",
            "| Evidence ID | Domain | Source Type | Field | State | Conf | Extractor | Lineage |",
            "| :--- | :--- | :--- | :--- | :---: | :---: | :--- | :--- |"
        ])

        for r in evidence_records[:60]:
            eid = r.get("evidence_id", "N/A")
            dom = r.get("domain", "PE")
            stype = r.get("source_type", "UNKNOWN")
            fld = r.get("field", "N/A")
            st = r.get("state", "OBSERVED")
            cnf = r.get("confidence", 1.0)
            ext = r.get("extractor", "Core")
            parents = ", ".join(r.get("parent_evidence_ids", [])) or "ROOT"
            lines.append(f"| `{eid}` | {dom} | {stype} | {fld} | {st} | {cnf:.2f} | {ext} | `{parents}` |")

        lines.extend([
            "",
            "---",
            "",
            "## 22. Analysis Manifest & Provenance",
            "",
            f"- **Engine Name:** {manifest.get('engine_name', '0206')}",
            f"- **Engine Version:** {manifest.get('engine_version', '2.0.0')}",
            f"- **Python Version:** {manifest.get('python_version', '3.x')}",
            f"- **Host Platform:** {manifest.get('host_platform', 'Linux')}",
            f"- **Execution Profile:** {manifest.get('profile', 'basic')}",
            f"- **Privacy Mode:** {manifest.get('privacy_mode', 'strict')}",
            f"- **Duration:** {(manifest.get('duration_ms') or 0.0):.2f} ms",
            f"- **Sample SHA256:** `{manifest.get('sample_sha256', 'N/A')}`",
            ""
        ])

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_path
