"""
0206 - Built-in Generic DOCX Report Adapter
Creates a clean, elegant, professional DOCX report from scratch using python-docx.
Completely decoupled from any proprietary external templates.
"""
from pathlib import Path
from typing import Dict, Any
import docx
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from report.adapters.base_adapter import BaseReportAdapter


class GenericDOCXReportAdapter(BaseReportAdapter):
    """Programmatically generates self-contained DOCX reports without external templates."""

    def render(self, session_data: Dict[str, Any], output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest = session_data.get("manifest", {})
        assessment = session_data.get("assessment", {})
        findings = session_data.get("findings", [])

        doc = docx.Document()

        # Set standard margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # Title
        title_p = doc.add_paragraph()
        run_title = title_p.add_run("MALWARE TRIAGE & FORENSIC ASSESSMENT REPORT")
        run_title.font.name = "Calibri"
        run_title.font.size = Pt(18)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(16, 44, 87)

        sub_p = doc.add_paragraph()
        run_sub = sub_p.add_run(f"Generated by 0206 Engine v{manifest.get('engine_version', '2.0.0')} | Case: {manifest.get('case_id', 'N/A')}")
        run_sub.font.size = Pt(10)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(100, 100, 100)

        # 1. Executive Summary Table
        doc.add_heading("1. Analysis Overview", level=1)
        meta_table = doc.add_table(rows=6, cols=2)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = False

        overview_data = [
            ("Target Sample", manifest.get("sample_filename", "Unknown")),
            ("File Size", f"{manifest.get('sample_size_bytes', 0):,} bytes"),
            ("SHA256 Hash", manifest.get("sample_hashes", {}).get("sha256", "N/A")),
            ("Threat Assessment", f"{assessment.get('threat_level', 'UNKNOWN')} (Score: {assessment.get('threat_score', 0)}/100)"),
            ("Malware Family / Class", assessment.get("classification", "Generic")),
            ("Analysis Timestamp (UTC)", manifest.get("start_time_utc", "N/A"))
        ]

        for i, (label, val) in enumerate(overview_data):
            r = meta_table.rows[i]
            r.cells[0].text = label
            r.cells[1].text = val
            r.cells[0].paragraphs[0].runs[0].font.bold = True
            r.cells[0].paragraphs[0].runs[0].font.size = Pt(9.5)
            r.cells[1].paragraphs[0].runs[0].font.size = Pt(9.5)

        # Executive narrative
        p_exec = doc.add_paragraph()
        p_exec.paragraph_format.space_before = Pt(8)
        run_exec = p_exec.add_run(assessment.get("summary", "No summary generated."))
        run_exec.font.size = Pt(10)

        # 2. Technical Findings Table
        doc.add_heading("2. Grounded Technical Findings", level=1)
        if findings:
            find_table = doc.add_table(rows=len(findings) + 1, cols=5)
            find_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            headers = ["ID", "Level", "Category", "Finding Details", "Evidence IDs"]
            hdr_cells = find_table.rows[0].cells
            for j, h in enumerate(headers):
                hdr_cells[j].text = h
                hdr_cells[j].paragraphs[0].runs[0].font.bold = True
                hdr_cells[j].paragraphs[0].runs[0].font.size = Pt(9)

            for idx, f in enumerate(findings):
                row = find_table.rows[idx + 1]
                eids = ", ".join(f.get("source_evidence_ids", [])) or "None"
                row.cells[0].text = f.get("finding_id", "")
                row.cells[1].text = f.get("evidence_level", "")
                row.cells[2].text = f.get("category", "")
                row.cells[3].text = f.get("title", "")
                row.cells[4].text = eids
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8.5)
        else:
            doc.add_paragraph("No technical findings derived.")

        # 3. Indicators of Compromise
        doc.add_heading("3. Indicators of Compromise (IOCs)", level=1)
        p_host = doc.add_paragraph()
        p_host.add_run("Host-based Indicators:\n").font.bold = True
        for h in assessment.get("host_iocs", []):
            p_host.add_run(f"  • {h}\n").font.size = Pt(9)
        if not assessment.get("host_iocs"):
            p_host.add_run("  • No host IOCs identified.\n").font.size = Pt(9)

        p_net = doc.add_paragraph()
        p_net.add_run("Network-based Indicators:\n").font.bold = True
        for n in assessment.get("network_iocs", []):
            p_net.add_run(f"  • {n}\n").font.size = Pt(9)
        if not assessment.get("network_iocs"):
            p_net.add_run("  • No network IOCs identified.\n").font.size = Pt(9)

        # 4. MITRE ATT&CK Mapping
        doc.add_heading("4. MITRE ATT&CK Techniques", level=1)
        mitre_list = assessment.get("mitre_techniques", [])
        if mitre_list:
            m_table = doc.add_table(rows=len(mitre_list) + 1, cols=4)
            m_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            m_headers = ["Technique ID", "Name", "Tactic", "Evidence IDs"]
            for k, h in enumerate(m_headers):
                m_table.rows[0].cells[k].text = h
                m_table.rows[0].cells[k].paragraphs[0].runs[0].font.bold = True
                m_table.rows[0].cells[k].paragraphs[0].runs[0].font.size = Pt(9)

            for idx, m in enumerate(mitre_list):
                row = m_table.rows[idx + 1]
                row.cells[0].text = m.get("technique_id", "")
                row.cells[1].text = m.get("technique_name", "")
                row.cells[2].text = m.get("tactic", "")
                row.cells[3].text = ", ".join(m.get("evidence_ids", []))
                for c in row.cells:
                    c.paragraphs[0].runs[0].font.size = Pt(8.5)

        # 5. Incident Response Recommendations
        doc.add_heading("5. Incident Response Recommendations", level=1)
        for r in assessment.get("recommendations", []):
            doc.add_paragraph(f"☐ {r}")

        doc.save(str(output_path))
        return output_path
