"""
0206 - Markdown Report Adapter
Renders evidence-grounded findings into GitHub-flavored Markdown.
"""
from pathlib import Path
from typing import Dict, Any
from report.adapters.base_adapter import BaseReportAdapter


class MarkdownReportAdapter(BaseReportAdapter):
    """Renders session findings into standalone Markdown report."""

    def render(self, session_data: Dict[str, Any], output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        manifest = session_data.get("manifest", {})
        assessment = session_data.get("assessment", {})
        findings = session_data.get("findings", [])
        evidence_records = session_data.get("evidence_records", [])

        lines = [
            f"# 🛡️ Malware Triage Report: {manifest.get('sample_filename', 'Unknown Sample')}",
            "",
            f"> **Generated by:** {manifest.get('engine_name', '0206')} v{manifest.get('engine_version', '2.0.0')}  ",
            f"> **Case ID:** `{manifest.get('case_id', 'N/A')}`  ",
            f"> **Analysis Date:** `{manifest.get('start_time_utc', 'N/A')}`  ",
            f"> **Threat Score:** `{assessment.get('threat_score', 0)}/100` ({assessment.get('threat_level', 'UNKNOWN')})  ",
            f"> **Classification:** `{assessment.get('classification', 'Generic')}`",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            "",
            assessment.get("summary", "No summary provided."),
            "",
            f"**Key Functionality:** {assessment.get('key_functionality', 'N/A')}",
            "",
            f"**Suspected Purpose:** {assessment.get('purpose', 'N/A')}",
            "",
            f"**Persistence Assessment:** {assessment.get('persistence_assessment', 'N/A')}",
            "",
            "---",
            "",
            "## 2. Technical Findings (Derived Inferences)",
            "",
            "| Finding ID | Level | Category | Title | Grounding Evidence | MITRE |",
            "| :--- | :---: | :--- | :--- | :--- | :---: |"
        ]

        for f in findings:
            eids = ", ".join(f.get("source_evidence_ids", [])) or "None"
            mitre = f.get("mitre_attack_id") or "N/A"
            lines.append(
                f"| `{f.get('finding_id')}` | **{f.get('evidence_level')}** | {f.get('category')} | {f.get('title')} | `{eids}` | `{mitre}` |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 3. Indicators of Compromise (Grounded IOCs)",
            "",
            "### Host-based Indicators",
            ""
        ])

        host_iocs = assessment.get("host_iocs", [])
        if host_iocs:
            for h in host_iocs:
                lines.append(f"- `{h}`")
        else:
            lines.append("- *No confirmed host IOCs identified.*")

        lines.extend([
            "",
            "### Network-based Indicators",
            ""
        ])
        net_iocs = assessment.get("network_iocs", [])
        if net_iocs:
            for n in net_iocs:
                lines.append(f"- `{n}`")
        else:
            lines.append("- *No confirmed network IOCs identified.*")

        lines.extend([
            "",
            "---",
            "",
            "## 4. MITRE ATT&CK Mapping",
            "",
            "| Technique ID | Technique Name | Tactic | Citing Evidence |",
            "| :--- | :--- | :--- | :--- |"
        ])

        for m in assessment.get("mitre_techniques", []):
            eids = ", ".join(m.get("evidence_ids", []))
            lines.append(
                f"| `{m.get('technique_id')}` | {m.get('technique_name')} | {m.get('tactic')} | `{eids}` |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 5. Incident Response Recommendations",
            ""
        ])

        for rec in assessment.get("recommendations", []):
            lines.append(f"- [ ] {rec}")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_path
