"""
0206 - AI Prompts Package
"""
from ai.prompts.part1_basic import BASIC_SYSTEM_PROMPT, BASIC_USER_PROMPT_TEMPLATE
from ai.prompts.part2_advanced import ADVANCED_SYSTEM_PROMPT, ADVANCED_USER_PROMPT_TEMPLATE

# Backward compatibility aliases
GROUNDED_SYSTEM_PROMPT = BASIC_SYSTEM_PROMPT
GROUNDED_USER_PROMPT_TEMPLATE = BASIC_USER_PROMPT_TEMPLATE

__all__ = [
    "BASIC_SYSTEM_PROMPT",
    "BASIC_USER_PROMPT_TEMPLATE",
    "ADVANCED_SYSTEM_PROMPT",
    "ADVANCED_USER_PROMPT_TEMPLATE",
    "GROUNDED_SYSTEM_PROMPT",
    "GROUNDED_USER_PROMPT_TEMPLATE",
]
